### ISSUE TITLE
How can I change the name of the file?

### ISSUE THREAD

**Issue by eddyhdzg** [Kalissaac/prisma-typegen#4]
The name of the file is "index.ts" by default, can it have another name?

**Comment by Kalissaac** [comment]
Completed in v0.0.7 (https://github.com/Kalissaac/prisma-typegen/commit/c502bd1fda55b64032cc86411724983d889356c6)

You can now specify the entire file path to choose a different file name:
```sh
$ npx @kalissaac/prisma-typegen ./interfaces/prismaTypes.ts ./schema.prisma
```
